name: build

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            {
              name: windows-latest,
              build_path: out/Grace-win32-x64,
              artifact: Grace-win32-x64,
            },
            {
              name: ubuntu-latest,
              build_path: out/Grace-linux-x64,
              artifact: Grace-linux-x64,
            },
          ]

    runs-on: ${{ matrix.os.name }}

    steps:
      - name: conferir o repositório git
        uses: actions/checkout@v4
      - name: instalar o node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: instalar dependências
        run: yarn
      - name: lint
        run: yarn lint
      - name: instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: instalar dependências
        run: pip install -r requirements.txt
      - name: construir com o pyinstaller
        run: pyinstaller torrent-client/main.py --distpath resources/dist --icon=images/icon.ico -n grace-download-manager
      - name: publicar
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STEAMGRIDDB_API_KEY: ${{ secrets.STEAMGRIDDB_API_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN }}
      - name: criar artefato
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.artifact }}
          path: ${{ matrix.os.build_path }}